MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 54000
  STEPS: [0, 32000, 45000]
# RESNETS:
#   RES5_DILATION: 2
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  ROI_MAX_LEVEL: 4
  ROI_MIN_LEVEL: 2
  RPN_ASPECT_RATIOS: (0.8, 1, 1.25)
  RPN_ANCHOR_START_SIZE: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  WEIGHTS: ./models/R-50.pkl
  DATASETS: ('coco_nucleus_train', 'coco_nucleus_val')
  SCALES: (971,)
  MAX_SIZE: 1413
  BATCH_SIZE_PER_IM: 768
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  IMS_PER_BATCH: 1
  USE_FLIPPED: False
  RPN_FG_FRACTION: 0.75
TEST:
  DATASETS: ('coco_nucleus_tt',)
  SCALE: 971
  MAX_SIZE: 1413
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  DETECTIONS_PER_IM: 350
  FORCE_JSON_DATASET_EVAL: True
OUTPUT_DIR: .
